baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Esther-Phebe A. Temenu"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Esther-Phebe A. Temenu"
author = "Esther-Phebe Temenu"
description = """
Super Software Engineer
Writing from Lagos,Nigeria
"""
profilePicture = "images/profile.jpg"
readMore = true

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:phebetemenu45@gmail.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/EstherPhebe"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/phebetemenu"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/esther_phebe"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
