baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Esther-Phebe A. Temenu"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Phebe A. Temenu"
author = "Phebe Temenu"
description = """
Backend and Cloud Developer 
Lagos, Nigeria.
"""
profilePicture = "images/profile.jpg"
readMore = true
mainSections = ["post"]

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:phebetemenu45@gmail.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/EstherPhebe"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/phebetemenu"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/esther_phebe"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main.main]]
  name = "Bio"
  weight = 300
  identifier = "bio"

  [[menu.main]]
  name = "About"
  weight = 310
  identifier = "about"
  url = "/about/"
  parent = "bio" 

  # [[menu.main]]
  # name = "Elevator Pitch"
  # weight = 320
  # identifier = "elevator-pitch"
  # url = "/elevator-pitch/"
  # parent = "bio" 

  [[menu.main]]
  name = "Portfolio"
  weight = 400
  identifier = "portfolio"
  url = "/portfolio/"
